version: "3"
services:
  mysqldb:
    image: mysql:8
    networks:
      - autocomplete-mysql
    environment:
      - MYSQL_DATABASE=db_event
      - MYSQL_ROOT_PASSWORD= 

  autocomplete-api:
    build:
      context: autocomplete-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - autocomplete-mysql
    depends_on:
      - mysqldb
      
  shoppingtimeline-api:
    build:
      context: shoppingTimeline-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      
networks:
  autocomplete-mysql:
